Repository Foxy/foxy-elements, pull requests merged in 2021-07, with the labels that each got.

#41 feat(admin): add error log UI
  custom-elements.json
  src/elements/public/ErrorEntryCard/DataList.ts
  src/elements/public/ErrorEntryCard/ErrorEntryCard.stories.ts
  src/elements/public/ErrorEntryCard/ErrorEntryCard.test.ts
  src/elements/public/ErrorEntryCard/ErrorEntryCard.ts
  src/elements/public/ErrorEntryCard/ResourceViewer.ts
  src/elements/public/ErrorEntryCard/index.ts
  src/elements/public/ErrorEntryCard/types.ts
Labels: enhancement

#46 feat: add user elements
  src/elements/private/Checkbox/Checkbox.ts
  src/elements/public/UserForm/UserForm.stories.ts
  src/elements/public/UserForm/UserForm.test.ts
  src/elements/public/UserForm/UserForm.ts
  src/elements/public/UserForm/index.ts
  src/elements/public/UserForm/roles.ts
  src/elements/public/UserForm/types.ts
  src/elements/public/UsersTable/UsersTable.stories.ts
  src/elements/public/UsersTable/UsersTable.test.ts
  src/elements/public/UsersTable/UsersTable.ts
  src/elements/public/UsersTable/index.ts
  src/elements/public/UsersTable/types.ts
  src/server/DemoDatabase.ts
  src/server/admin/composers/composeUser.ts
  src/server/admin/index.ts
  src/server/dump.json
  src/static/translations/shared/en.json
  src/static/translations/shared/es.json
Labels: enhancement

#49 build: lock node version to 14
  .nvmrc
Labels: bug

#52 feat: release v1.5.0
  package-lock.json
  package.json
  src/elements/private/Choice/Choice.test.ts
  src/elements/public/CollectionPages/CollectionPages.ts
  src/elements/public/Customer/Customer.stories.ts
  src/elements/public/Customer/Customer.test.ts
  src/elements/public/Customer/Customer.ts
  src/elements/public/Customer/types.ts
  src/elements/public/CustomerPortal/CustomerPortal.stories.ts
  src/elements/public/CustomerPortal/InternalCustomerPortalSubscriptions.test.ts
  src/elements/public/CustomerPortal/InternalCustomerPortalSubscriptions.ts
  src/elements/public/CustomerPortal/InternalCustomerPortalTransactions.test.ts
  src/elements/public/CustomerPortal/InternalCustomerPortalTransactions.ts
  src/elements/public/CustomerPortal/types.ts
  src/elements/public/ErrorEntryCard/ErrorEntryCard.test.ts
  src/elements/public/NucleonElement/NucleonElement.ts
  src/elements/public/SignInForm/SignInForm.ts
  src/elements/public/SubscriptionCard/SubscriptionCard.stories.ts
  src/elements/public/SubscriptionCard/SubscriptionCard.test.ts
  src/elements/public/SubscriptionCard/SubscriptionCard.ts
  src/elements/public/SubscriptionCard/index.ts
  src/elements/public/SubscriptionCard/types.ts
  src/elements/public/SubscriptionsTable/types.ts
  src/elements/public/Table/Table.test.ts
  src/elements/public/Table/Table.ts
  src/elements/public/Table/index.ts
  src/elements/public/Table/types.ts
  src/elements/public/TransactionsTable/types.ts
  src/elements/public/UserForm/UserForm.ts
  src/elements/public/index.defined.ts
  src/elements/public/index.ts
  src/server/DemoDatabase.ts
  src/storygen/getMetaArgTypes.ts
  src/storygen/getStoryArgs.ts
Labels: bug, enhancement
